import 'Anastasia Script.ttf';
import 'Brusher.ttf';
import 'Candy Butterfly.ttf';
import 'Debby.ttf';
import 'COOPBL.TTF';
import 'Capinella ou Beaujoais.ttf';
import 'VLADIMIR.TTF';
import 'Srinthile Script.ttf';
import 'Satherday.otf';
import 'Santa Story ttf.ttf';
import 'src/fonts/Masterics.ttf';
import 'magnolia_sky.ttf';
import 'Lobster-Regular.ttf';
import 'Libertinage.ttf';
import 'I Love Glitter - TTF.ttf';
import 'Hillary Youth.ttf';
import 'Granotta Regular.ttf';
import 'Girlish.otf';
import 'Gabrielly.ttf';
import 'EmbassyBT.ttf';
import 'Delisha Glande.ttf';
import 'KAUFMANN.TTF';
import 'KUNSTLER.TTF';
import 'mr_DopestyleG.otf'