export * from './card/Card';
export * from './main/Main';
export * from './header/Header';
export * from './changeText/ChangeText';
export * from './cards/Cards';
export * from './modal/Modal';
export * from './chooseColor/ChooseColor';
export * from './select/Select';
export * from './modalMainContent/ModalMainContent';
export * from './chooseBgColor/ChooseBgColor';
export * from './chooseFontSize/ChooseFontSize';
export * from './footer/Footer'